model:
  category: DeepSeek
  model_name_or_path: deepseek-chat
  api_key: sk-779d1bfeeb1a4f38bc219b163f034c51
  base_url: https://api.deepseek.com

extraction:
  task: NER
  text: The Sustainability World Summit 2025, organized by Key Notion, will take place from June 11 to June 13 in Frankfurt, Germany. This premier event focuses on driving sustainable business through innovation, featuring industry leaders and expert insights. # input text for the extraction task. No need if use_file is set to true.
  constraint: ["algorithm", "conference", "else", "product", "task", "field", "metrics", "organization", "researcher", "program language", "country", "location", "person", "university"] # Specified entity types for the named entity recognition task. Default set to empty.
  use_file: false
  mode: quick
  update_case: false
  show_trajectory: false
