model:
  category: DeepSeek
  model_name_or_path: deepseek-chat
  api_key: sk-779d1bfeeb1a4f38bc219b163f034c51
  base_url: https://api.deepseek.com

extraction:
  task: RE  # task type, chosen from Base, NER, RE, EE.
  text: Greek authorities ordered thousands to evacuate from different parts of the southern island of Crete, one of the country's most popular tourist spots, where wildfires burned uncontrollably on Thursday. Firefighters were struggling to contain the blaze as gale-force winds fueled the flames.  # input text for the extraction task. No need if use_file is set to true.
  constraint: ["nationality", "country capital", "place of death", "children", "location contains", "place of birth", "place lived", "administrative division of country", "country of administrative divisions", "company", "neighborhood of", "company founders"] # Specified entity types for the named entity recognition task. Default set to empty.
  truth: {"relation_list": [{"head": "Greece", "tail": "Crete", "relation": "administrative division of country"}]} # Truth data for the relation extraction task. Structured as a dictionary with the list of relation tuples as the value. Required if set update_case to true.
  use_file: false # whether to use a file for the input text.
  mode: quick # extraction mode, chosen from quick, detailed, customized. Default set to quick. See src/config.yaml for more details.
  update_case: true # whether to update the case repository. Default set to false.
  show_trajectory: false # whether to display the extracted intermediate steps
