model:
  category: DeepSeek
  model_name_or_path: deepseek-chat
  api_key: sk-779d1bfeeb1a4f38bc219b163f034c51
  base_url: https://api.deepseek.com

extraction:
  mode: quick # extraction mode, chosen from quick, detailed, customized. Default set to quick. See src/config.yaml for more details.
  task: Triple  # task type, chosen from Base, NER, RE, EE. Now newly added task 'Triple'.
  use_file: true # whether to use a file for the input text. Default set to false.
  file_path: ./data/input_files/Batman_Wikipedia.txt #  # path to the input file. No need if use_file is set to false.
  constraint: [["Person", "Place", "Event", "Property"], ["Interpersonal", "Located", "Ownership", "Action"]] # Specified entity or relation types for Triple Extraction task. You can write 3 lists for subject, relation and object types. Or you can write 2 lists for entity and relation types. Or you can write 1 list for entity type only.
  update_case: false # whether to update the case repository. Default set to false.
  show_trajectory: false # whether to display the extracted intermediate steps

construct: # (Optional) If you want to construct a Knowledge Graph, you need to set the construct field, or you must delete this field.
   database: Neo4j # database type, now only support Neo4j.
   url: neo4j+s://52bb44ac.databases.neo4j.io # your database URL，Neo4j's default port is 7687.
   username: neo4j # your database username.
   password: "JjvWjR1XEBr-6hHYh1oAmlekinaNgl7xhWfRY0pGZP4" # your database password.
